### ISSUE TITLE
Access from other devices on local network

### ISSUE THREAD

**Issue by Appex213** [Crivella/ocr_translate#30]
Is there a way to access the server from outside of localhost? 

I'm using the release version for windows and can't get the server to run with an address that isn't localhost to get the server to be visible on the local network. Is there something I'm missing?

**Comment by Crivella** [comment]
There are 2 sides to this problem:

- The way the server is being run
- The Django settings, in particular https://docs.djangoproject.com/en/5.0/ref/settings/#allowed-hosts

On the first part if you are using the EXE, the script running the server is baked into the EXE and it is being run by binding the server to local host.
You would need to either follow the instruction on  the docs (https://crivella.github.io/ocr_translate/running/from_github.html) and substitute the last command to execute by binding to 0.0.0.0   ->  `python manage.py runserver 0.0.0.0:PORT`
Or use the docker container as there gunicorn is already set to bind to 0.0.0.0 (https://github.com/Crivella/ocr_translate/blob/95b26839d9d95103214caee419a33cb7b2bbad9f/start-server.sh#L44)

On the second part, again if you are using the bundled EXE i am not sure there is a non hacky way of changing the line to add whatever [the ](https://github.com/Crivella/ocr_translate/blob/95b26839d9d95103214caee419a33cb7b2bbad9f/mysite/settings.py#L106).
While following the instruction you can just edit that line to add the host you want to allow, (and in case you are using docker you will need to go into the running container `docker exec -it CONTAINER_NAME /bin/bash` and edit it from inside and restart the server.

Let me know if this works for you

**Comment by Crivella** [comment]
PS if there is request for this i might check on a few way to make this easier to do also using the EXE, but consider that right now the server is not build to handle large volumes (using more dedicated services to enable this would require complicating the installation a lot, eg people would need to set up and configure those services beside running the EXE), in case of multiple users there would also be the problem of who controls what model are loaded
