### ISSUE TITLE
invalid command 'bdist_wheel'

### ISSUE THREAD

**Issue by FrAn3k-arch** [Crivella/ocr_translate#40]
Hello. I have a problem with installing several plugins, I get an error during installation "invalid command 'bdist_wheel'"
Plugins are:
 unidic-lite==1.0.8
googletrans==4.0.0rc1

[wheel.txt](https://github.com/user-attachments/files/17790932/wheel.txt)
![Zrzut ekranu 2024-11-17 145745](https://github.com/user-attachments/assets/4a3ed06a-ec15-4bdc-80b6-4c911985b300)
![Zrzut ekranu 2024-11-17 154243](https://github.com/user-attachments/assets/be416fdc-1f33-4435-a501-c6503832fde3)
![Zrzut ekranu 2024-11-17 154531](https://github.com/user-attachments/assets/846c058d-ae8b-41bf-9847-dbe8db3254e7)

**Comment by Crivella** [comment]
This is related to #39.

You can have a python installation that does not come with `wheel` by default.
As a temporary solution, you can try the fix in the mentioned issue (https://github.com/Crivella/ocr_translate/issues/39#issuecomment-2476073982).

I've already pushed a fix for this and it will be in the next release (https://github.com/Crivella/ocr_translate/commit/94c5b1ba232be8ed3f583b5d2ce1eff6d09beeea)

**Comment by FrAn3k-arch** [comment]
thanks, now everything works
